import { NextResponse } from 'next/server'
import { getDb } from '@/lib/db'

export async function POST(request){
 const db=await getDb().getConnection()
 try{
  const body=await request.json(),empresaId=String(body.empresaId||''),localId=String(body.localEstoqueId||'')
  if(!/^\d+$/.test(empresaId)||!/^\d+$/.test(localId)||!/^\d{4}-\d{2}-\d{2}$/.test(body.data||'')||!Array.isArray(body.itens))return NextResponse.json({error:'Informe estoque, data e produtos válidos.'},{status:400})
  await db.beginTransaction()
  const[[local]]=await db.execute("SELECT id FROM locais_estoque WHERE id=? AND id_empresa=? AND status='ATIVO'",[localId,empresaId]);const[[user]]=await db.execute("SELECT id_usuario id FROM usuario_empresa WHERE id_empresa=? AND status='ATIVO' ORDER BY (id_usuario=?) DESC LIMIT 1",[empresaId,body.usuarioId||0]);if(!local||!user)throw Object.assign(new Error('Estoque ou usuário inválido.'),{status:400})
  for(const item of body.itens){const quantidade=Number(item.quantidade);if(!/^\d+$/.test(String(item.produtoId||''))||!Number.isFinite(quantidade)||quantidade<0)throw Object.assign(new Error('Existe uma quantidade inválida no balanço.'),{status:400});const[[produto]]=await db.execute("SELECT p.id,p.permite_producao,p.permite_venda,COALESCE(pe.custo_atual,0) custo FROM produtos p JOIN produto_empresa pe ON pe.id_produto=p.id WHERE p.id=? AND pe.id_empresa=?",[item.produtoId,empresaId]);if(!produto)throw Object.assign(new Error(`O produto ${item.produtoId} não pertence a esta empresa.`),{status:400});if((produto.permite_producao||produto.permite_venda)&&!Number.isInteger(quantidade))throw Object.assign(new Error('Produtos acabados devem ser contados em quantidades inteiras.'),{status:400});const[[saldo]]=await db.execute('SELECT id,quantidade FROM estoque WHERE id_empresa=? AND id_local_estoque=? AND id_produto=? FOR UPDATE',[empresaId,localId,item.produtoId]);const anterior=Number(saldo?.quantidade||0),diferenca=quantidade-anterior;if(saldo)await db.execute('UPDATE estoque SET quantidade=?,data_atualizacao=NOW() WHERE id=?',[quantidade,saldo.id]);else await db.execute('INSERT INTO estoque(id_empresa,id_local_estoque,id_produto,quantidade,quantidade_reservada)VALUES(?,?,?,?,0)',[empresaId,localId,item.produtoId,quantidade]);if(Math.abs(diferenca)>0.000001)await db.execute(`INSERT INTO movimentacao_estoque(id_empresa,id_local_estoque,id_produto,tipo,quantidade,valor_total,origem_tipo,id_usuario,data_movimentacao,observacao)VALUES(?,?,?,?,?,?,'BALANCO_ESTOQUE',?,?,?)`,[empresaId,localId,item.produtoId,diferenca>0?'AJUSTE_ENTRADA':'AJUSTE_SAIDA',Math.abs(diferenca),Math.abs(diferenca)*Number(produto.custo),user.id,`${body.data} 12:00:00`,`Balanço de estoque: saldo anterior ${anterior}; saldo contado ${quantidade}`])}
  await db.commit();return NextResponse.json({message:'Balanço concluído e ajustes registrados no Kardex.'})
 }catch(error){await db.rollback();console.error('Erro no balanço de estoque:',error);return NextResponse.json({error:error.message||'Não foi possível concluir o balanço.'},{status:error.status||500})}finally{db.release()}
}
