ALTER TABLE item_nota_fiscal
  ADD COLUMN id_cor INT NULL AFTER id_produto,
  ADD COLUMN id_tamanho INT NULL AFTER id_cor,
  ADD COLUMN id_modelo INT NULL AFTER id_tamanho,
  ADD COLUMN tipo_valor ENUM('UNITARIO','METRO','TOTAL') NOT NULL DEFAULT 'UNITARIO' AFTER unidade,
  ADD CONSTRAINT fk_item_nf_cor FOREIGN KEY (id_cor) REFERENCES cores(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  ADD CONSTRAINT fk_item_nf_tamanho FOREIGN KEY (id_tamanho) REFERENCES tamanhos(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  ADD CONSTRAINT fk_item_nf_modelo FOREIGN KEY (id_modelo) REFERENCES modelos(id) ON UPDATE CASCADE ON DELETE RESTRICT;
