'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import PageHeader from '@/components/common/page-header'
import StatusBadge from '@/components/common/status-badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { useAuth } from '@/lib/auth-context'
import { useEntity } from '@/lib/data-store'
import { Factory, Pencil, ShoppingCart, Truck, CheckCircle2, PackagePlus } from 'lucide-react'
import { toast } from 'sonner'
import { Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle,DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { formatQuantity } from '@/lib/number-format'

export default function OPDetalhe(){
  const{id}=useParams();const{user}=useAuth();const{data:estoques}=useEntity('locais_estoque',user?.empresaId);const[order,setOrder]=useState(null);const[sendQty,setSendQty]=useState('');const[showDetails,setShowDetails]=useState(false);const[saving,setSaving]=useState(false);const[finishOpen,setFinishOpen]=useState(false);const[finishStock,setFinishStock]=useState('');const[produced,setProduced]=useState({})
  const reload=()=>fetch(`/api/production-orders/${id}?empresaId=${user.empresaId}`).then(r=>r.json()).then(setOrder)
  useEffect(()=>{if(user?.empresaId)reload()},[id,user?.empresaId])
  const transferir=async(enviarTodos=false)=>{setSaving(true);try{const r=await fetch(`/api/production-orders/${id}/transfer`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresaId:user.empresaId,usuarioId:user.id,quantidade:Number(sendQty),enviarTodos})});const b=await r.json();if(!r.ok)throw new Error(b.error);toast.success(b.message);setSendQty('');await reload()}catch(e){toast.error(e.message)}finally{setSaving(false)}}
  const receber=async()=>{setSaving(true);try{const r=await fetch(`/api/production-orders/${id}/transfer`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresaId:user.empresaId,usuarioId:user.id})});const b=await r.json();if(!r.ok)throw new Error(b.error);toast.success(b.message);await reload()}catch(e){toast.error(e.message)}finally{setSaving(false)}}
  const concluir=async()=>{setSaving(true);try{const r=await fetch(`/api/production-orders/${id}/complete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresaId:user.empresaId,usuarioId:user.id,localEstoqueId:finishStock,itens:order.items.map(x=>({itemId:x.id,quantidade:Number(produced[x.id]||0)}))})});const b=await r.json();if(!r.ok)throw new Error(b.error);toast.success(b.message);setFinishOpen(false);setProduced({});await reload()}catch(e){toast.error(e.message)}finally{setSaving(false)}}
  if(!order)return <p className="text-sm text-muted-foreground">Carregando ordem…</p>
  const hasItems=Boolean(order.items?.length)
  const canFinish=order.items?.some(item=>Number(item.quantidadeUltimoSetor)>Number(item.quantidadeProduzida||0))
  const consumoConsolidado=Array.from((order.consumption||[]).reduce((map,row)=>{const current=map.get(String(row.materiaPrimaId))||{...row,necessario:0,disponivel:0,faltante:0};current.necessario+=Number(row.necessario);current.disponivel+=Number(row.disponivel);current.faltante+=Number(row.faltante);map.set(String(row.materiaPrimaId),current);return map},new Map()).values())
  return <div className="space-y-5"><PageHeader title={`OP ${order.numero}`} description={`${order.setor} · ${formatQuantity(order.quantidadePlanejada)} peças planejadas`} icon={Factory}><div className="flex gap-2"><Link href={`/ordens-producao/${id}/produto`}><Button variant="outline" className="gap-2">{hasItems?<Pencil className="h-4 w-4"/>:<PackagePlus className="h-4 w-4"/>}{hasItems?'Editar produto':'Adicionar produto'}</Button></Link>{canFinish&&!['concluida','cancelada','aguardando_material'].includes(order.status)&&<Dialog open={finishOpen} onOpenChange={setFinishOpen}><DialogTrigger asChild><Button className="gap-2"><CheckCircle2 className="h-4 w-4"/>Registrar produção concluída</Button></DialogTrigger><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Registrar peças concluídas da OP {order.numero}</DialogTitle></DialogHeader><div className="space-y-4"><div className="space-y-1.5"><Label>Estoque de destino</Label><Select value={finishStock} onValueChange={setFinishStock}><SelectTrigger><SelectValue placeholder="Selecione o estoque"/></SelectTrigger><SelectContent>{estoques.map(x=><SelectItem key={x.id} value={String(x.id)}>{x.nome}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2">{order.items.map(x=>{const remaining=Number(x.quantidadeUltimoSetor)-Number(x.quantidadeProduzida||0);return <div key={x.id} className="grid grid-cols-[1fr_140px] items-center gap-3 rounded-md border p-3"><div><div className="font-medium">{x.produto} — {x.cor} / {x.tamanho}</div><div className="text-xs text-muted-foreground">Disponível no último setor: {formatQuantity(remaining)}</div></div><Input type="number" min="0" max={remaining} step="1" value={produced[x.id]||''} onChange={e=>setProduced(v=>({...v,[x.id]:e.target.value}))} placeholder="Qtd. concluída" disabled={remaining<=0}/></div>})}</div></div><DialogFooter><Button variant="outline" onClick={()=>setFinishOpen(false)}>Cancelar</Button><Button onClick={concluir} disabled={saving||!finishStock}>{saving?'Processando…':'Confirmar entrada no estoque'}</Button></DialogFooter></DialogContent></Dialog>}</div></PageHeader>
    <div className="grid grid-cols-2 md:grid-cols-5 gap-3"><Info label="Status"><StatusBadge status={order.status}/></Info><Info label="Prioridade"><StatusBadge status={String(order.prioridade).toLowerCase()}/></Info><Info label="Setor atual" value={order.setor}/><Info label="Abertura" value={order.dataAbertura}/><Info label="Prazo" value={order.prazoConclusao||'—'}/></div>
    <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle className="text-base">Fluxo dos produtos</CardTitle><p className="mt-1 text-sm text-muted-foreground">Acompanhe cada cor e tamanho em todos os setores.</p></div><Button asChild><Link href={`/ordens-producao/${id}/movimentacoes`}><Truck className="mr-2 h-4 w-4"/>Abrir movimentações</Link></Button></CardHeader><CardContent className="space-y-3">
      <div className="flex flex-wrap gap-2">{order.fluxo?.map((f,i)=><span key={f.id} className={`rounded-full px-3 py-1 text-sm ${String(f.setorId)===String(order.setorId)?'company-primary-bg text-primary-foreground':'bg-secondary'}`}>{i+1}. {f.setor}</span>)}</div>
      {order.movimentacaoPendente&&<p className="rounded border border-amber-500/30 bg-amber-500/10 p-3 text-sm">Existe um lote a caminho de <strong>{order.movimentacaoPendente.setorDestino}</strong>. Abra as movimentações para conferir as variações e confirmar a chegada.</p>}
      {!canFinish&&<p className="text-sm text-muted-foreground">O registro no estoque será liberado quando alguma peça chegar ao último setor.</p>}
    </CardContent></Card>
    <Card><CardHeader className="flex-row items-center justify-between gap-3"><button type="button" className="text-left" onClick={()=>setShowDetails(v=>!v)}><CardTitle className="text-base">{order.items?.[0]?.produto||'Produto acabado'}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{formatQuantity(order.quantidadePlanejada)} peças planejadas · clique para {showDetails?'ocultar':'ver'} os detalhes</p></button><Button asChild variant="outline" size="sm"><Link href={`/ordens-producao/${id}/produto`}><Pencil className="mr-2 h-4 w-4"/>Editar produto</Link></Button></CardHeader>{showDetails&&<CardContent><Table><TableHeader><TableRow><TableHead>Cor</TableHead><TableHead>Tamanho</TableHead><TableHead className="text-right">Planejado</TableHead><TableHead className="text-right">Produzido</TableHead></TableRow></TableHeader><TableBody>{order.items.map(item=><TableRow key={item.id}><TableCell>{item.cor||'—'}</TableCell><TableCell>{item.tamanho||'—'}</TableCell><TableCell className="text-right">{formatQuantity(item.quantidade)}</TableCell><TableCell className="text-right">{formatQuantity(item.quantidadeProduzida)}</TableCell></TableRow>)}</TableBody></Table></CardContent>}</Card>
    <Card><CardHeader className="flex-row items-center justify-between"><CardTitle className="text-base">Matérias-primas consolidadas</CardTitle><Link href={`/ordens-producao/${id}/consumo`}><Button variant="outline" size="sm">Editar consumo</Button></Link></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Matéria-prima</TableHead><TableHead className="text-right">Necessário</TableHead><TableHead className="text-right">Disponível utilizado</TableHead><TableHead className="text-right">Faltante</TableHead></TableRow></TableHeader><TableBody>{consumoConsolidado.map(row=><TableRow key={row.materiaPrimaId}><TableCell>{row.materiaPrima}</TableCell><TableCell className="text-right">{formatQuantity(row.necessario)} {row.unidade}</TableCell><TableCell className="text-right">{formatQuantity(row.disponivel)} {row.unidade}</TableCell><TableCell className={`text-right ${Number(row.faltante)>0?'text-red-400':'text-emerald-400'}`}>{formatQuantity(row.faltante)} {row.unidade}</TableCell></TableRow>)}</TableBody></Table>{order.pedidoCompra&&<div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-md border border-amber-500/30 bg-amber-500/10 p-3 text-sm"><span>Material insuficiente: compra <strong>{order.pedidoCompra}</strong> gerada automaticamente.</span>{order.pedidoCompraId&&<Button asChild size="sm" variant="outline"><Link href={`/compras/${order.pedidoCompraId}`}>Abrir compra</Link></Button>}</div>}</CardContent></Card>
    <div><Link href="/ordens-producao"><Button variant="outline">Voltar para Ordens de Produção</Button></Link></div>
  </div>
}
function Info({label,value,children}){return <Card><CardContent className="p-4"><div className="text-xs uppercase text-muted-foreground">{label}</div><div className="mt-1 font-medium">{children||value}</div></CardContent></Card>}
