'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import PageHeader from '@/components/common/page-header'
import StatusBadge from '@/components/common/status-badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { useAuth } from '@/lib/auth-context'
import { useEntity } from '@/lib/data-store'
import { Factory, Pencil, ShoppingCart, Truck, CheckCircle2, PackagePlus } from 'lucide-react'
import { toast } from 'sonner'
import { Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle,DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'

export default function OPDetalhe(){
  const{id}=useParams();const{user}=useAuth();const{data:setores}=useEntity('setores',user?.empresaId);const{data:estoques}=useEntity('locais_estoque',user?.empresaId);const[order,setOrder]=useState(null);const[destino,setDestino]=useState('');const[saving,setSaving]=useState(false);const[finishOpen,setFinishOpen]=useState(false);const[finishStock,setFinishStock]=useState('');const[produced,setProduced]=useState({})
  const reload=()=>fetch(`/api/production-orders/${id}?empresaId=${user.empresaId}`).then(r=>r.json()).then(setOrder)
  useEffect(()=>{if(user?.empresaId)reload()},[id,user?.empresaId])
  const transferir=async()=>{if(!destino)return toast.error('Selecione o setor de destino.');setSaving(true);try{const r=await fetch(`/api/production-orders/${id}/transfer`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresaId:user.empresaId,usuarioId:user.id,setorDestinoId:destino})});const b=await r.json();if(!r.ok)throw new Error(b.error);toast.success(b.message);setDestino('');await reload()}catch(e){toast.error(e.message)}finally{setSaving(false)}}
  const receber=async()=>{setSaving(true);try{const r=await fetch(`/api/production-orders/${id}/transfer`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresaId:user.empresaId,usuarioId:user.id})});const b=await r.json();if(!r.ok)throw new Error(b.error);toast.success(b.message);await reload()}catch(e){toast.error(e.message)}finally{setSaving(false)}}
  const concluir=async()=>{setSaving(true);try{const r=await fetch(`/api/production-orders/${id}/complete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresaId:user.empresaId,usuarioId:user.id,localEstoqueId:finishStock,itens:order.items.map(x=>({itemId:x.id,quantidade:Number(produced[x.id]||0)}))})});const b=await r.json();if(!r.ok)throw new Error(b.error);toast.success(b.message);setFinishOpen(false);setProduced({});await reload()}catch(e){toast.error(e.message)}finally{setSaving(false)}}
  if(!order)return <p className="text-sm text-muted-foreground">Carregando ordem…</p>
  const hasItems=Boolean(order.items?.length)
  return <div className="space-y-5"><PageHeader title={`OP ${order.numero}`} description={`${order.setor} · ${Number(order.quantidadePlanejada)} peças planejadas`} icon={Factory}><div className="flex gap-2"><Link href={`/ordens-producao/${id}/produto`}><Button variant="outline" className="gap-2">{hasItems?<Pencil className="h-4 w-4"/>:<PackagePlus className="h-4 w-4"/>}{hasItems?'Editar produtos':'Adicionar produtos'}</Button></Link>{hasItems&&!['concluida','cancelada','aguardando_material'].includes(order.status)&&<Dialog open={finishOpen} onOpenChange={setFinishOpen}><DialogTrigger asChild><Button className="gap-2"><CheckCircle2 className="h-4 w-4"/>Registrar produção</Button></DialogTrigger><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Registrar produção da OP {order.numero}</DialogTitle></DialogHeader><div className="space-y-4"><div className="space-y-1.5"><Label>Estoque de destino</Label><Select value={finishStock} onValueChange={setFinishStock}><SelectTrigger><SelectValue placeholder="Selecione o estoque"/></SelectTrigger><SelectContent>{estoques.map(x=><SelectItem key={x.id} value={String(x.id)}>{x.nome}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2">{order.items.map(x=>{const remaining=Number(x.quantidade)-Number(x.quantidadeProduzida||0);return <div key={x.id} className="grid grid-cols-[1fr_140px] items-center gap-3 rounded-md border p-3"><div><div className="font-medium">{x.produto} — {x.cor} / {x.tamanho}</div><div className="text-xs text-muted-foreground">Planejado: {Number(x.quantidade)} · Produzido: {Number(x.quantidadeProduzida||0)} · Restante: {remaining}</div></div><Input type="number" min="0" max={remaining} step="1" value={produced[x.id]||''} onChange={e=>setProduced(v=>({...v,[x.id]:e.target.value}))} placeholder="Qtd. produzida" disabled={remaining<=0}/></div>})}</div></div><DialogFooter><Button variant="outline" onClick={()=>setFinishOpen(false)}>Cancelar</Button><Button onClick={concluir} disabled={saving||!finishStock}>{saving?'Processando…':'Confirmar entrada'}</Button></DialogFooter></DialogContent></Dialog>}</div></PageHeader>
    <div className="grid grid-cols-2 md:grid-cols-5 gap-3"><Info label="Status"><StatusBadge status={order.status}/></Info><Info label="Prioridade"><StatusBadge status={String(order.prioridade).toLowerCase()}/></Info><Info label="Setor atual" value={order.setor}/><Info label="Abertura" value={order.dataAbertura}/><Info label="Prazo" value={order.prazoConclusao||'—'}/></div>
    <Card><CardHeader><CardTitle className="text-base">Movimentação entre setores</CardTitle></CardHeader><CardContent className="space-y-4">
      {order.movimentacaoPendente ? <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 rounded-md border border-amber-500/30 bg-amber-500/10 p-4"><div><div className="font-medium flex items-center gap-2"><Truck className="h-4 w-4"/>A caminho de {order.movimentacaoPendente.setorDestino}</div><div className="text-xs text-muted-foreground mt-1">Saiu de {order.movimentacaoPendente.setorOrigem || '—'} em {order.movimentacaoPendente.dataEnvio}</div></div><Button onClick={receber} disabled={saving} className="gap-2"><CheckCircle2 className="h-4 w-4"/>Marcar como entregue</Button></div> : <div className="flex flex-col sm:flex-row sm:items-end gap-3"><div className="space-y-1.5 flex-1 max-w-md"><Label>Enviar para outro setor</Label><Select value={destino} onValueChange={setDestino}><SelectTrigger><SelectValue placeholder="Selecione o destino"/></SelectTrigger><SelectContent>{setores.filter(s=>s.status==='ativo'&&String(s.id)!==String(order.setorId)).map(s=><SelectItem key={s.id} value={String(s.id)}>{s.nome}</SelectItem>)}</SelectContent></Select></div><Button onClick={transferir} disabled={saving||!destino} className="gap-2"><Truck className="h-4 w-4"/>Enviar ordem</Button></div>}
      <Table><TableHeader><TableRow><TableHead>Origem</TableHead><TableHead>Destino</TableHead><TableHead>Status</TableHead><TableHead>Envio</TableHead><TableHead>Entrega</TableHead></TableRow></TableHeader><TableBody>{!order.movimentacoes?.length&&<TableRow><TableCell colSpan={5} className="text-center text-muted-foreground">Sem movimentações.</TableCell></TableRow>}{order.movimentacoes?.map(m=><TableRow key={m.id}><TableCell>{m.setorOrigem||'Início'}</TableCell><TableCell>{m.setorDestino}</TableCell><TableCell><StatusBadge status={m.status}/></TableCell><TableCell>{m.dataEnvio}</TableCell><TableCell>{m.dataRecebimento||'—'}</TableCell></TableRow>)}</TableBody></Table>
    </CardContent></Card>
    <Card><CardHeader className="flex-row items-center justify-between gap-3"><CardTitle className="text-base">Produtos da ordem</CardTitle><Button asChild variant={hasItems?'outline':'default'} size="sm" className="gap-2"><Link href={`/ordens-producao/${id}/produto`}>{hasItems?<Pencil className="h-4 w-4"/>:<PackagePlus className="h-4 w-4"/>}{hasItems?'Editar produtos':'Adicionar produto'}</Link></Button></CardHeader><CardContent>{!hasItems?<div className="rounded-lg border border-dashed p-8 text-center"><PackagePlus className="mx-auto mb-3 h-8 w-8 text-muted-foreground"/><p className="font-medium">Nenhum produto adicionado</p><p className="mt-1 text-sm text-muted-foreground">Adicione os produtos, cores, tamanhos e quantidades que serão produzidos.</p></div>:<Table><TableHeader><TableRow><TableHead>Produto</TableHead><TableHead>Cor</TableHead><TableHead>Tamanho</TableHead><TableHead className="text-right">Planejado</TableHead><TableHead className="text-right">Produzido</TableHead></TableRow></TableHeader><TableBody>{order.items.map(item=><TableRow key={item.id}><TableCell>{item.produto}</TableCell><TableCell>{item.cor}</TableCell><TableCell>{item.tamanho}</TableCell><TableCell className="text-right">{Number(item.quantidade)}</TableCell><TableCell className="text-right">{Number(item.quantidadeProduzida||0)}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card>
    <Card><CardHeader className="flex-row items-center justify-between"><CardTitle className="text-base">Planejamento de matéria-prima</CardTitle>{hasItems?<Link href={`/ordens-producao/${id}/consumo`}><Button variant="outline" size="sm">Editar consumo</Button></Link>:<Button variant="outline" size="sm" disabled>Adicione produtos primeiro</Button>}</CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Variação</TableHead><TableHead>Matéria-prima</TableHead><TableHead className="text-right">Por peça</TableHead><TableHead className="text-right">Necessário</TableHead><TableHead className="text-right">Disponível utilizado</TableHead><TableHead className="text-right">Faltante</TableHead></TableRow></TableHeader><TableBody>{order.consumption?.map(row=>{const item=order.items.find(i=>String(i.id)===String(row.itemId));return <TableRow key={row.id}><TableCell>{item?.cor} / {item?.tamanho}</TableCell><TableCell>{row.materiaPrima}</TableCell><TableCell className="text-right">{Number(row.porPeca)} {row.unidade}</TableCell><TableCell className="text-right">{Number(row.necessario)} {row.unidade}</TableCell><TableCell className="text-right">{Number(row.disponivel)} {row.unidade}</TableCell><TableCell className={`text-right ${Number(row.faltante)>0?'text-red-400':'text-emerald-400'}`}>{Number(row.faltante)} {row.unidade}</TableCell></TableRow>})}</TableBody></Table>{order.pedidoCompra&&<div className="mt-4 flex items-center justify-between rounded-md border border-amber-500/30 bg-amber-500/10 p-3"><span className="text-sm">Material insuficiente: pedido <strong>{order.pedidoCompra}</strong> gerado automaticamente.</span><Link href="/compras"><Button size="sm" className="gap-2"><ShoppingCart className="h-4 w-4"/>Ver compra</Button></Link></div>}</CardContent></Card>
    <div><Link href="/ordens-producao"><Button variant="outline">Voltar para Ordens de Produção</Button></Link></div>
  </div>
}
function Info({label,value,children}){return <Card><CardContent className="p-4"><div className="text-xs uppercase text-muted-foreground">{label}</div><div className="mt-1 font-medium">{children||value}</div></CardContent></Card>}
