'use client'
import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import PageHeader from '@/components/common/page-header'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { useEntity } from '@/lib/data-store'
import { useAuth } from '@/lib/auth-context'
import { Grid3X3, Plus, Trash2 } from 'lucide-react'
import { toast } from 'sonner'

export default function ProdutoOPPage(){
  const{id}=useParams();const router=useRouter();const{user}=useAuth();const{data:all}=useEntity('produtos',user?.empresaId);const products=all.filter(p=>p.tipo==='produto_acabado')
  const[order,setOrder]=useState(null);const[picker,setPicker]=useState('');const[selected,setSelected]=useState([]);const[quantities,setQuantities]=useState({});const[saving,setSaving]=useState(false)
  useEffect(()=>{if(!user?.empresaId)return;fetch(`/api/production-orders/${id}?empresaId=${user.empresaId}`).then(r=>r.json()).then(body=>{setOrder(body);if(body.items?.length){setSelected(Array.from(new Set(body.items.map(x=>x.produtoId))));setQuantities(Object.fromEntries(body.items.map(x=>[`${x.produtoId}:${x.corId}:${x.tamanhoId}`,Number(x.quantidade)])))}})},[id,user?.empresaId])
  const total=Object.values(quantities).reduce((s,v)=>s+Number(v||0),0);const key=(p,c,t)=>`${p}:${c}:${t}`
  const add=()=>{if(!picker)return;setSelected(prev=>prev.includes(picker)?prev:[...prev,picker]);setPicker('')};const remove=productId=>{setSelected(prev=>prev.filter(x=>x!==productId));setQuantities(prev=>Object.fromEntries(Object.entries(prev).filter(([k])=>!k.startsWith(`${productId}:`))))}
  const save=async()=>{const items=[];for(const productId of selected){const product=products.find(p=>p.id===productId);for(const v of product?.variacoes||[]){const quantidade=Number(quantities[key(productId,v.corId,v.tamanhoId)]||0);if(quantidade>0)items.push({produtoId:productId,corId:v.corId,tamanhoId:v.tamanhoId,quantidade})}}setSaving(true);try{const response=await fetch(`/api/production-orders/${id}/items`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresaId:user.empresaId,items})});const body=await response.json();if(!response.ok)throw new Error(body.error);toast.success(`Planejamento salvo com ${total} peças.`);router.push(`/ordens-producao/${id}/consumo`)}catch(error){toast.error(error.message)}finally{setSaving(false)}}
  if(!order)return <p className="text-sm text-muted-foreground">Carregando ordem…</p>
  return <div className="space-y-5"><PageHeader title={`OP ${order.numero} — produtos`} description="Adicione um ou mais produtos e informe as quantidades por cor e tamanho" icon={Grid3X3}/><Card><CardContent className="p-5 flex flex-col sm:flex-row gap-2"><Select value={picker} onValueChange={setPicker}><SelectTrigger className="max-w-xl"><SelectValue placeholder="Selecione um produto acabado"/></SelectTrigger><SelectContent>{products.filter(p=>!selected.includes(p.id)).map(p=><SelectItem key={p.id} value={p.id}>{p.nome} ({p.codigo})</SelectItem>)}</SelectContent></Select><Button type="button" onClick={add} disabled={!picker} className="gap-2"><Plus className="h-4 w-4"/>Adicionar produto</Button></CardContent></Card>
  {selected.map(productId=>{const product=products.find(p=>p.id===productId);if(!product)return null;const variations=product.variacoes||[];const colors=Array.from(new Map(variations.map(v=>[v.corId,{id:v.corId,nome:v.cor}])).values());const sizes=Array.from(new Map(variations.map(v=>[v.tamanhoId,{id:v.tamanhoId,nome:v.tamanho}])).values());return <Card key={productId}><CardHeader className="flex-row items-center justify-between"><CardTitle className="text-base">{product.nome}</CardTitle><Button variant="ghost" size="icon" className="text-red-400" onClick={()=>remove(productId)}><Trash2 className="h-4 w-4"/></Button></CardHeader><CardContent>{!variations.length?<p className="text-sm text-amber-400">Cadastre cores e tamanhos neste produto antes de usá-lo.</p>:<div className="overflow-x-auto rounded-lg border"><table className="min-w-full text-sm"><thead><tr className="bg-secondary/60"><th className="p-3 text-left">Cores \ Tamanhos</th>{sizes.map(s=><th key={s.id} className="p-3 text-center min-w-28">{s.nome}</th>)}</tr></thead><tbody>{colors.map(c=><tr key={c.id} className="border-t"><th className="p-3 text-left">{c.nome}</th>{sizes.map(s=>{const allowed=variations.some(v=>v.corId===c.id&&v.tamanhoId===s.id);const k=key(productId,c.id,s.id);return <td key={s.id} className="p-2">{allowed?<Input type="number" min="0" step="1" className="text-center" value={quantities[k]||''} onChange={e=>setQuantities(prev=>({...prev,[k]:e.target.value}))} placeholder="0"/>:<div className="text-center text-muted-foreground">—</div>}</td>})}</tr>)}</tbody></table></div>}</CardContent></Card>})}
  <Card className="bg-secondary/20"><CardContent className="p-4 flex flex-wrap items-center justify-between gap-3"><div><div className="text-sm text-muted-foreground">Quantidade planejada calculada</div><div className="text-2xl font-semibold">{total} peças</div><div className="text-xs text-muted-foreground">Soma de todos os produtos, cores e tamanhos preenchidos.</div></div><div className="flex gap-2"><Button variant="outline" onClick={()=>router.push('/ordens-producao')}>Cancelar</Button><Button onClick={save} disabled={saving||total<=0}>{saving?'Salvando…':'Continuar para consumo'}</Button></div></CardContent></Card></div>
}
