'use client'
import { useEffect,useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'
import PageHeader from '@/components/common/page-header'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select'
import { useAuth } from '@/lib/auth-context'
import { FilePlus } from 'lucide-react'
import { toast } from 'sonner'
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export default function NovaNota(){const router=useRouter();const{user}=useAuth();const[compras,setCompras]=useState([]);const[detalhe,setDetalhe]=useState(null);const[saving,setSaving]=useState(false);const[form,setForm]=useState({compraId:'',numero:'',numeroAutomatico:true,serie:'1',chave:'',dataEmissao:new Date().toISOString().slice(0,10),observacao:''});const set=(k,v)=>setForm(p=>({...p,[k]:v}));useEffect(()=>{if(!user?.empresaId)return;fetch(`/api/compras?empresaId=${user.empresaId}`).then(r=>r.json()).then(setCompras).catch(()=>toast.error('Não foi possível carregar as compras.'))},[user?.empresaId]);const disponiveis=useMemo(()=>compras.filter(x=>x.status==='emitida'),[compras]);const choose=async id=>{set('compraId',id);const r=await fetch(`/api/compras/${id}?empresaId=${user.empresaId}`);const b=await r.json();if(!r.ok)return toast.error(b.error);setDetalhe(b)};const save=async e=>{e.preventDefault();setSaving(true);try{const r=await fetch('/api/notas-fiscais',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,empresaId:user.empresaId,usuarioId:user.id})});const b=await r.json();if(!r.ok)throw new Error(b.error);toast.success('Nota recebida, compra entregue e estoque atualizado.');router.push(`/notas-fiscais/${b.id}`)}catch(e){toast.error(e.message)}finally{setSaving(false)}}
 return <div className="space-y-6"><PageHeader title="Nova nota fiscal" description="A nota deve corresponder a uma compra emitida. Os produtos serão recebidos automaticamente." icon={FilePlus}/><form onSubmit={save} className="space-y-6"><Card><CardHeader><CardTitle className="text-base">Dados da nota fiscal</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Compra obrigatória *"><Select value={form.compraId} onValueChange={choose}><SelectTrigger><SelectValue placeholder="Selecione a compra"/></SelectTrigger><SelectContent>{disponiveis.map(x=><SelectItem key={x.id} value={String(x.id)}>{x.codigo} — {x.fornecedor}</SelectItem>)}</SelectContent></Select></Field><Field label="Número da nota"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.numeroAutomatico} onChange={e=>set('numeroAutomatico',e.target.checked)}/>Gerar automaticamente</label>{!form.numeroAutomatico&&<Input className="mt-2" value={form.numero} onChange={e=>set('numero',e.target.value)} required/>}</Field><Field label="Série *"><Input value={form.serie} onChange={e=>set('serie',e.target.value)} required/></Field><Field label="Data de emissão *"><Input type="date" value={form.dataEmissao} onChange={e=>set('dataEmissao',e.target.value)} required/></Field><div className="md:col-span-2 xl:col-span-4"><Field label="Chave de acesso *"><Input value={form.chave} onChange={e=>set('chave',e.target.value)} maxLength={44} required/></Field></div></CardContent></Card>{detalhe&&<Card><CardHeader><CardTitle className="text-base">Produtos recebidos da compra {detalhe.codigo}</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><Info label="Fornecedor" value={detalhe.fornecedor}/><Info label="Estoque de destino" value={detalhe.estoque}/></div><div className="overflow-x-auto rounded-lg border"><table className="w-full text-sm"><thead className="bg-secondary/60"><tr><th className="px-3 py-2 text-left">Produto</th><th className="px-3 py-2 text-left">Quantidade</th><th className="px-3 py-2 text-left">Valor unitário</th><th className="px-3 py-2 text-left">Total</th></tr></thead><tbody>{detalhe.itens.map(x=><tr className="border-t" key={x.id}><td className="px-3 py-3 font-medium">{x.nome}</td><td className="px-3 py-3">{x.quantidade} {x.unidade}</td><td className="px-3 py-3">{money(x.valorUnitario)}</td><td className="px-3 py-3">{money(x.valorTotal)}</td></tr>)}</tbody></table></div></CardContent></Card>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>router.push('/notas-fiscais')}>Cancelar</Button><Button disabled={saving||!detalhe} className="company-primary-bg text-primary-foreground">{saving?'Processando…':'Cadastrar e receber nota'}</Button></div></form></div>}
function Field({label,children}){const hint=label.startsWith('Série')?'Identifica a sequência de numeração utilizada pelo emissor da nota fiscal.':label.startsWith('Chave de acesso')?'Código numérico de 44 dígitos que identifica a NF-e na Secretaria da Fazenda.':label.startsWith('Compra obrigatória')?'Compra cujos produtos serão recebidos por esta nota fiscal.':'';return <div className="space-y-1.5"><Label title={hint} className={hint?'cursor-help underline decoration-dotted underline-offset-4':''}>{label}{hint&&' ⓘ'}</Label>{children}</div>}function Info({label,value}){return <div><div className="text-xs text-muted-foreground">{label}</div><div className="font-medium">{value}</div></div>}
