'use client'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import PageHeader from '@/components/common/page-header'
import QuickCreateDialog from '@/components/common/quick-create-dialog'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { useAuth } from '@/lib/auth-context'
import { useEntity } from '@/lib/data-store'
import { formatQuantity } from '@/lib/number-format'
import { ArrowLeft, ClipboardCheck, Pencil, Plus, Trash2 } from 'lucide-react'
import { toast } from 'sonner'

export default function BalancoEstoquePage(){
 const router=useRouter(),{user}=useAuth(),saldos=useEntity('estoque',user?.empresaId),locais=useEntity('locais_estoque',user?.empresaId),produtosStore=useEntity('produtos',user?.empresaId),categorias=useEntity('categorias',user?.empresaId),cores=useEntity('cores',user?.empresaId),tamanhos=useEntity('tamanhos',user?.empresaId)
 const[localId,setLocalId]=useState(''),[tipo,setTipo]=useState('todos'),[data,setData]=useState(new Date().toISOString().slice(0,10)),[itens,setItens]=useState([]),[produtoAdicionar,setProdutoAdicionar]=useState(''),[saving,setSaving]=useState(false)
 const materias=produtosStore.data.filter(p=>p.tipo==='materia_prima')
 const saldosVersion=saldos.data.map(x=>`${x.estoqueId}:${x.produtoId}:${x.total}`).join('|')
 useEffect(()=>{if(!localId){setItens([]);return}const rows=saldos.data.filter(x=>String(x.estoqueId)===localId).map(x=>({produtoId:String(x.produtoId),nome:x.produto,codigo:x.codigo,tipo:x.tipo,unidade:produtosStore.data.find(p=>String(p.id)===String(x.produtoId))?.unidade||x.unidadeMinimo,anterior:Number(x.total),quantidade:String(Number(x.total))}));setItens(rows)},[localId,saldosVersion])
 const visiveis=itens.filter(x=>tipo==='todos'||x.tipo===tipo),disponiveis=useMemo(()=>produtosStore.data.filter(p=>(tipo==='todos'||p.tipo===tipo)&&!itens.some(x=>String(x.produtoId)===String(p.id))),[produtosStore.data,itens,tipo])
 const adicionar=id=>{const p=produtosStore.data.find(x=>String(x.id)===String(id));if(!p)return;setItens(v=>[...v,{produtoId:String(p.id),nome:p.nome,codigo:p.codigo,tipo:p.tipo,unidade:p.unidade,anterior:0,quantidade:'0'}]);setProdutoAdicionar('')}
 const concluir=async()=>{if(!localId)return toast.error('Selecione o estoque.');setSaving(true);try{const response=await fetch('/api/stock/balance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresaId:user.empresaId,usuarioId:user.id,localEstoqueId:localId,data,itens:itens.map(x=>({produtoId:x.produtoId,quantidade:Number(x.quantidade)}))})}),body=await response.json();if(!response.ok)throw new Error(body.error);toast.success(body.message);await saldos.reload();router.push('/estoque')}catch(error){toast.error(error.message)}finally{setSaving(false)}}
 return <div className="space-y-5"><PageHeader title="Balanço de estoque" description="Conte os produtos e ajuste o saldo real com registro automático no Kardex" icon={ClipboardCheck}><Button asChild variant="outline"><Link href="/estoque"><ArrowLeft className="mr-2 h-4 w-4"/>Voltar ao estoque</Link></Button></PageHeader>
  <Card><CardContent className="grid gap-4 p-5 md:grid-cols-3"><Field label="Estoque"><Select value={localId} onValueChange={setLocalId}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{locais.data.filter(x=>x.status==='ativo').map(x=><SelectItem key={x.id} value={String(x.id)}>{x.nome}</SelectItem>)}</SelectContent></Select></Field><Field label="Tipo de produto"><Select value={tipo} onValueChange={setTipo}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="todos">Todos</SelectItem><SelectItem value="materia_prima">Matéria-prima</SelectItem><SelectItem value="produto_acabado">Produto acabado</SelectItem></SelectContent></Select></Field><Field label="Data do balanço"><Input type="date" value={data} onChange={e=>setData(e.target.value)}/></Field></CardContent></Card>
  {localId&&<Card><CardContent className="space-y-4 p-5"><div className="flex flex-wrap gap-2"><Select value={produtoAdicionar} onValueChange={setProdutoAdicionar}><SelectTrigger className="max-w-md"><SelectValue placeholder="Adicionar produto existente ao balanço"/></SelectTrigger><SelectContent>{disponiveis.map(p=><SelectItem key={p.id} value={String(p.id)}>{p.codigo} · {p.nome} ({p.unidade})</SelectItem>)}</SelectContent></Select><Button variant="secondary" disabled={!produtoAdicionar} onClick={()=>adicionar(produtoAdicionar)}><Plus className="mr-2 h-4 w-4"/>Adicionar</Button><QuickCreateDialog label="Cadastrar novo produto" defaults={{tipo:'materia_prima',unidade:'unidade',status:true,minimo:0,codigoAutomatico:true,corIds:[],tamanhoIds:[],insumos:[]}} fields={[{name:'nome',label:'Nome',required:true},{name:'codigo',label:'Código',type:'uniqueCode',required:true},{name:'tipo',label:'Tipo',type:'select',required:true,options:[{value:'materia_prima',label:'Matéria-prima'},{value:'produto_acabado',label:'Produto acabado'}]},{name:'insumos',label:'Matérias-primas por unidade',type:'recipe',required:true,showWhen:f=>f.tipo==='produto_acabado',options:materias.map(x=>({value:String(x.id),label:`${x.nome} (${x.unidade})`}))},{name:'unidade',label:'Unidade',type:'select',required:true,showWhen:f=>f.tipo==='materia_prima',options:[{value:'unidade',label:'Unidade'},{value:'metro',label:'Metro'},{value:'kg',label:'Quilograma'},{value:'outros',label:'Outros'}]},{name:'categoriaId',label:'Categoria',type:'select',required:true,showWhen:f=>f.tipo==='produto_acabado',options:categorias.data.map(x=>({value:String(x.id),label:x.nome}))},{name:'corIds',label:'Cores',type:'multiselect',options:cores.data.filter(x=>x.status==='ativo').map(x=>({value:String(x.id),label:x.nome}))},{name:'tamanhoIds',label:'Tamanhos',type:'multiselect',options:tamanhos.data.map(x=>({value:String(x.id),label:x.nome}))},{name:'minimo',label:'Quantidade mínima',type:'number',required:true}]} onCreate={async values=>{const novo=await produtosStore.create({...values,unidade:values.tipo==='produto_acabado'?'unidade':values.unidade,status:'ativo'});setItens(v=>[...v,{produtoId:String(novo.id),nome:novo.nome,codigo:novo.codigo,tipo:novo.tipo,unidade:novo.unidade||'unidade',anterior:0,quantidade:'0'}])}}/></div>
   <div className="overflow-x-auto rounded border"><table className="w-full text-sm"><thead className="bg-secondary/60"><tr><th className="p-3 text-left">Produto</th><th className="p-3 text-right">Saldo anterior</th><th className="p-3 text-right">Quantidade contada</th><th className="p-3"></th></tr></thead><tbody>{visiveis.map(item=><tr key={item.produtoId} className="border-t"><td className="p-3"><div className="font-medium">{item.nome}</div><div className="text-xs text-muted-foreground">{item.codigo} · {item.unidade}</div></td><td className="p-3 text-right">{formatQuantity(item.anterior)}</td><td className="p-3"><Input className="ml-auto max-w-36 text-right" type="number" min="0" step={item.tipo==='produto_acabado'?'1':'0.01'} value={item.quantidade} onChange={e=>setItens(v=>v.map(x=>x.produtoId===item.produtoId?{...x,quantidade:e.target.value}:x))}/></td><td className="p-3 text-right"><Button asChild variant="ghost" size="icon" title="Editar produto"><Link href={`/produtos?editar=${item.produtoId}`} target="_blank"><Pencil className="h-4 w-4"/></Link></Button>{item.anterior===0&&<Button variant="ghost" size="icon" className="text-red-400" title="Retirar do balanço" onClick={()=>setItens(v=>v.filter(x=>x.produtoId!==item.produtoId))}><Trash2 className="h-4 w-4"/></Button>}</td></tr>)}</tbody></table>{!visiveis.length&&<p className="p-8 text-center text-muted-foreground">Nenhum produto neste estoque para o filtro selecionado.</p>}</div>
  </CardContent></Card>}
  <div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>router.push('/estoque')}>Cancelar</Button><Button disabled={saving||!localId||!data} onClick={concluir}>{saving?'Concluindo…':'Concluir balanço'}</Button></div>
 </div>
}
function Field({label,children}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
