import { NextResponse } from 'next/server'
import { getDb } from '@/lib/db'

export async function GET(request,{params}){try{const{id}=await params;const empresaId=new URL(request.url).searchParams.get('empresaId');const[[compra]]=await getDb().execute(`SELECT c.id,c.codigo,c.origem,LOWER(c.status) status,DATE_FORMAT(c.data_emissao,'%Y-%m-%d') dataEmissao,c.observacao,
  CAST(c.id_local_estoque AS CHAR) estoqueId,le.nome estoque,CAST(c.id_fornecedor AS CHAR) fornecedorId,COALESCE(f.nome_fantasia,f.razao_social) fornecedor,op.numero ordemProducao
  FROM compras c JOIN locais_estoque le ON le.id=c.id_local_estoque JOIN fornecedores f ON f.id=c.id_fornecedor LEFT JOIN ordem_producao op ON op.id=c.id_ordem_producao WHERE c.id=? AND c.id_empresa=?`,[id,empresaId]);if(!compra)return NextResponse.json({error:'Compra não encontrada.'},{status:404});const[itens]=await getDb().execute(`SELECT ci.id,CAST(ci.id_produto AS CHAR) produtoId,p.codigo,p.nome,p.unidade,CAST(ci.id_cor AS CHAR) corId,co.nome cor,CAST(ci.id_tamanho AS CHAR) tamanhoId,t.nome tamanho,ci.quantidade,ci.valor_unitario valorUnitario,ci.valor_total valorTotal FROM compra_itens ci JOIN produtos p ON p.id=ci.id_produto LEFT JOIN cores co ON co.id=ci.id_cor LEFT JOIN tamanhos t ON t.id=ci.id_tamanho WHERE ci.id_compra=? ORDER BY p.nome`,[id]);return NextResponse.json({...compra,id:String(compra.id),itens})}catch(error){return NextResponse.json({error:'Não foi possível carregar a compra.'},{status:500})}}

export async function PUT(request,{params}){const connection=await getDb().getConnection();try{const{id}=await params;const body=await request.json();await connection.beginTransaction();const[[compra]]=await connection.execute('SELECT id,status,origem FROM compras WHERE id=? AND id_empresa=? FOR UPDATE',[id,body.empresaId]);if(!compra)throw Object.assign(new Error('Compra não encontrada.'),{status:404});if(compra.origem==='ORDEM_PRODUCAO')throw Object.assign(new Error('Compras geradas por ordem de produção não permitem alterar os dados gerais.'),{status:409});if(compra.status==='ENTREGUE')throw Object.assign(new Error('Compra entregue não pode ser editada.'),{status:409});await connection.execute(`UPDATE compras SET id_local_estoque=?,id_fornecedor=?,codigo=?,data_emissao=?,observacao=? WHERE id=?`,[body.estoqueId,body.fornecedorId,body.codigo,body.dataEmissao,body.observacao||null,id]);await connection.commit();return NextResponse.json({message:'Compra atualizada.'})}catch(error){await connection.rollback();return NextResponse.json({error:error.message},{status:error.status||500})}finally{connection.release()}}

export async function DELETE(request,{params}){const connection=await getDb().getConnection();try{const{id}=await params;const empresaId=new URL(request.url).searchParams.get('empresaId');await connection.beginTransaction();const[[compra]]=await connection.execute('SELECT status,origem FROM compras WHERE id=? AND id_empresa=? FOR UPDATE',[id,empresaId]);if(!compra)throw Object.assign(new Error('Compra não encontrada.'),{status:404});if(compra.status==='ENTREGUE'||compra.origem==='ORDEM_PRODUCAO')throw Object.assign(new Error('Esta compra não pode ser excluída.'),{status:409});await connection.execute('DELETE FROM compras WHERE id=?',[id]);await connection.commit();return new NextResponse(null,{status:204})}catch(error){await connection.rollback();return NextResponse.json({error:error.message},{status:error.status||500})}finally{connection.release()}}
